### ISSUE TITLE
Deployment documentation still lacks configuration parameters

### ISSUE THREAD

**Issue by haemka** [num-codex/codex-processes-ap1#123]
The [deployment documentation](https://github.com/num-codex/codex-processes-ap1/wiki/Process-Deployment-and-Configuration-v1.0.0.0) still lacks important and even the bare minimum of needed configuration parameters. 

It is infeasible for admins to read through the whole list of possible parameters and configure everything by trial and error.

Please update the documentation asap.

**Comment by schwzr** [comment]
As discussed in the consultation hour, we will add the required parameters for Risk Principe project as soon as we will publish the updated process plugin.
