### ISSUE TITLE
Add Feedback Messages and Delete of Binary Resources

### ISSUE THREAD

**Issue by hhund** [num-codex/codex-processes-ap1#36]
The `send`, `translate` and `receive` processes should be modified to include messages back from the CRR to the GTH and the GTH to the DIC. These Messages should be used to either relay successful transfer (maybe with some statistics) or errors such as validation errors at the CRR or an error communicating with the fTTP. A received message should trigger the deletion or permanent deletion of the encrypted Bundle (aka Binary resource). If no message is received a timer should remove the Binary resource.

**Comment by wetret** [comment]
Additionally, if an error has occurred, there should be a configuration possibility to be notified about the error via eMail.
