### ISSUE TITLE
CRR Pseudonym Needs Type Information

### ISSUE THREAD

**Issue by hhund** [num-codex/codex-processes-ap1#51]
Based on the latest [Patient profile](https://simplifier.net/forschungsnetzcovid-19/patient) all patient resource identifiers need a type declaration. In order to produce compliant Patient resources, we need to modify 

https://github.com/num-codex/codex-processes-ap1/blob/5e8e548786141021953c389d18d74e1a31609620/codex-process-data-transfer/src/main/java/de/netzwerk_universitaetsmedizin/codex/processes/data_transfer/service/ReadData.java#L180

**Comment by wetret** [comment]
The identifier should also be generated correctly after resolving the bloom-filter by adding the type information to this line of code:

https://github.com/num-codex/codex-processes-ap1/blob/5e8e548786141021953c389d18d74e1a31609620/codex-process-data-transfer/src/main/java/de/netzwerk_universitaetsmedizin/codex/processes/data_transfer/service/ResolvePseudonym.java#L97
