### ISSUE TITLE
Bundle Search URLs Should Be URL Escaped

### ISSUE THREAD

**Issue by hhund** [num-codex/codex-processes-ap1#53]
In order to maximize the compatibility of our batch search-bundle we should URL escape the the search queries. This is specially true for the `_lastUpdated` parameter.

Fix should be implemented in the modifySearchUrl Method:
https://github.com/num-codex/codex-processes-ap1/blob/5e8e548786141021953c389d18d74e1a31609620/codex-process-data-transfer/src/main/java/de/netzwerk_universitaetsmedizin/codex/processes/data_transfer/client/fhir/AbstractFhirClient.java#L326-L327

A workaround for the `http://www.netzwerk-universitaetsmedizin.de/fhir/CodeSystem/data-transfer|export-to` input parameter within the task-start-data-send Task might be to specify the timestamp via `2021-12-11T11:00:00Z` not `2021-12-11T11:00:00+01:00`.

**Comment by alexanderkiel** [comment]
It is not sufficient to specify a timestamp via the UTC timezone, because the process outputs all timestamps in the default java timezone. However it is possible to set the environment variable `TZ` to `UTC`.
