### ISSUE TITLE
Validator Generates False-Positives

### ISSUE THREAD

**Issue by hhund** [num-codex/codex-processes-ap1#72]
Effected process plugin version: 0.5.0

Due to an error in the StructureDefinition snapshot generator of HAPI 5.1.0, the validator produces false-positive errors. Effected StructureDefinitions validation rules from `de.gecco|1.0.5` and its depended implementation guides are:

* Observation.category.coding:blood-gas-studies
    [https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/pH|1.0.4](https://simplifier.net/packages/de.gecco/1.0.5/files/package/Profile-Observation-GasPanel-pH.json)
* Observation.category.coding:blood-gas-studies
    [https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/carbon-dioxide-partial-pressure|1.0.4](https://simplifier.net/packages/de.gecco/1.0.5/files/package/Profile-Observation-GasPanel-PaCO2.json)
* Observation.category.coding:blood-gas-studies
    [https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/oxygen-partial-pressure|1.0.4](https://simplifier.net/packages/de.gecco/1.0.5/files/package/Profile-Observation-GasPanel-PaO2.json)
* Observation.category.coding:blood-gas-studies
    [https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/inhaled-oxygen-concentration|1.0.4](https://simplifier.net/packages/de.gecco/1.0.5/files/package/Profile-Observation-FiO2.json)
* Condition.code.coding:orphanet
    [https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/diabetes-mellitus|1.0](https://simplifier.net/packages/de.gecco/1.0.5/files/package/Profile-Condition-DiabetesMellitus.json)
* Condition.code.coding:orphanet
    [https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/organ-recipient|1.0](https://simplifier.net/packages/de.gecco/1.0.5/files/package/Profile-Condition-OrganRecipient.json)
* Condition.code.coding:orphanet
    [https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/symptoms-covid-19|1.0](https://simplifier.net/packages/de.gecco/1.0.5/files/package/Profile-Condition-Symptoms-Covid-19.json)

A fix already exists for the following rule in the 0.5.0 release of the process plugin:
* Procedure.code.coding:dicom
    [https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/radiology-procedures|1.0.5](https://simplifier.net/packages/de.gecco/1.0.5/files/package/Profile-Procedure-Radiology.json)

Root cause of the false-positive validation errors are wrong generated "min = X" (for X != 0) rules in the StructureDefinition snapshot for slicing rules without a "min" definition where the slicing definition (incl. discriminator) is not part of the same profile but rather defined in the base profile.

The fix will include identifying bad profile rules and adding a `min 0` where appropriate. Similar to the existing fix: 

https://github.com/num-codex/codex-processes-ap1/blob/f5aaa4ec7d96ba42e3862d909a54e8ba0bd81129/codex-process-data-transfer/src/main/java/de/netzwerk_universitaetsmedizin/codex/processes/data_transfer/validation/structure_definition/GeccoRadiologyProceduresCodingSliceMinFixer.java#L15-L31

**Comment by taneroksuz** [comment]
We get follwing errors, when we validate our fhir bundle (only for testing purpose):  
  1. bpe-app-1  | ERROR pool-2-thread-1 - ValidateData.logValidationDetails(164) | Validation error for https://fhir-store-test.uk-augsburg.science/fhir/Observation/d2e193da2a246b87f4f1c5857eca2e71bb9bd514769ac77f53bdd17a894c06a4/_history/1 location Observation.value.ofType(Quantity).code: Value is '{breaths}/min' but must be '/min'
  2. bpe-app-1  | ERROR pool-2-thread-1 - ValidateData.logValidationDetails(164) | Validation error for https://fhir-store-test.uk-augsburg.science/fhir/Observation/7a23462b0b2743a3630177affdd9264a17dcc2ddb83b99ed4385a90d82def786/_history/1 location Observation: Profile https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/sars-cov-2-ab-pnl-ser-pl-ia, Element 'Observation.identifier': minimum required = 1, but only found 0
  3. bpe-app-1  | ERROR pool-2-thread-1 - ValidateData.logValidationDetails(164) | Validation error for https://fhir-store-test.uk-augsburg.science/fhir/Observation/7a23462b0b2743a3630177affdd9264a17dcc2ddb83b99ed4385a90d82def786/_history/1 location Observation: Profile https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/sars-cov-2-ab-pnl-ser-pl-ia, Element 'Observation.identifier[analyseBefundCode]': minimum required = 1, but only found 0
  4. bpe-app-1  | ERROR pool-2-thread-1 - ValidateData.logValidationDetails(164) | Validation error for https://fhir-store-test.uk-augsburg.science/fhir/Observation/e8b0bd67f9a5a2f689f7d2e1ea5c00d1b37214275a7f8300e71b9b0364447605/_history/1 location Observation.code: Profile https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/oxygen-partial-pressure, Element 'Observation.code.coding': minimum required = 1, but only found 0
  5. bpe-app-1  | ERROR pool-2-thread-1 - ValidateData.logValidationDetails(164) | Validation error for https://fhir-store-test.uk-augsburg.science/fhir/Observation/54cc3e37d808683f3331d7423eddaa667538ec387a7e2dd941c0b16b300d18d9/_history/1 location Observation.value.ofType(Quantity).code: Value is '{beats}/min' but must be '/min'
  6. bpe-app-1  | ERROR pool-2-thread-1 - ValidateData.logValidationDetails(164) | Validation error for https://fhir-store-test.uk-augsburg.science/fhir/Patient/1f06df569a74be3085a5b4dbfc31a3f09b32fc989b80ef4b39d39deefe272a5b/_history/3 location Patient.extension[0]: Profile https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/age, Element 'Patient.extension[0].extension[dateTimeOfDocumentation]': minimum required = 1, but only found 0

[Please download the fhir bundle with txt extension](https://github.com/num-codex/codex-processes-ap1/files/9008680/3640494350246c67f67c0d373afb7caec09bfeb43a965e7a8b57268b6f26fcdd.txt)

**Comment by hhund** [comment]
@taneroksuz Based on my understanding I am classifying the first two errors as false positive. 

* From a quick search the [SarsCoV2AbPnlSerPlIA](https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/sars-cov-2-ab-pnl-ser-pl-ia) profile is currently the only profile missing from our [ObservationIdentifierRemover](https://github.com/num-codex/codex-processes-ap1/blob/main/codex-process-data-transfer/src/main/java/de/netzwerk_universitaetsmedizin/codex/processes/data_transfer/validation/structure_definition/ObservationIdentifierRemover.java) class. As such it should be the last remaining profile suffering from the `analyseBefundCode` false positive error.

* The third error about `Observation.code.coding` seems to be correct since your code does not match one of the 3 codes allowed for that location in the [PaO2](https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/oxygen-partial-pressure) profile:
One of the following codes is expected:
    ```
    {
      "system": "http://loinc.org",
      "code": "11556-8"
    }
    
    {
      "system": "http://loinc.org",
      "code": "2703-7"
    }
    
    {
      "system": "http://loinc.org",
      "code": "2704-5"
    }
    ```
    The code `11557-8` from your example, does not seem to exist within the LOINC catalog ([Code Not Found](https://loinc.org/11557-8/)).

* The fourth error is also an error on your end. Within the [Age](https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/age) extension profile, the `data-absent-reason` extension is not allowed as a stand-in for the `dateTimeOfDocumentation` value. I may have misjudged this during the hackathon. My understanding now is, that the [Data Absent Reason](http://hl7.org/fhir/StructureDefinition/data-absent-reason) extension can only be used as a stand-in if it is explicitly allowed by the profile, e.g. in [MII Laboruntersuchung](https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/ObservationLab) as a stand-in for `Observation.value`.

**Comment by hhund** [comment]
In addition to the code `396332003+414029004` included in ValueSet [RheumatologicalImmunologicalDiseases](https://simplifier.net/packages/de.gecco/1.0.5/files/package/ValueSet-rheumatological-immunological-diseases.json) reported by @eicherj, the following SNOMED CT codes included in ValueSet [VaccinesSNOMED](https://simplifier.net/packages/de.gecco/1.0.5/files/package/ValueSet-vaccines-snomed.json) will currently (release 0.5.1) result in false-positive validation errors:
```
836498007+836388000
871729003+836380007+601000221108+863911006+836374004+871871008
871729003+836380007+601000221108+863911006+836374004
871729003+836374004+863911006
863911006+836374004+601000221108+836381006
836380007+1031000221108
871729003+836388000+863911006
836498007+836382004
836398006+836380007
836380007+601000221108
```

**Comment by hhund** [comment]
Hi @eicherj,

the GECCO profile [Respiratory Rate](https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/respiratory-rate) has a validation rule for `Observation.valueQuantity.code` defining a fixed value using the pattern: `/min`

Since `Observation.valueQuantity.code` is a primitive and the [FHIR R4 standard](https://www.hl7.org/fhir/R4/elementdefinition-definitions.html#ElementDefinition.pattern_x_) states
> When pattern[x] is used to constrain a primitive, it means that the value provided in the pattern[x] must match the instance value exactly.

the UCUM specification is ignored. Based on the current [Respiratory Rate](https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/respiratory-rate) profile, the validation error you mentioned above is not a false-positive, but rather a result of the way the GECCO profile is defined.

The validator from [simplifier.net](https://simplifier.net/validate?scope=ForschungsnetzCovid-19@current&fhirVersion=R4) seems to agree with this assessment.

@julsas Any thoughts on changing [Respiratory Rate](https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/respiratory-rate) and other profiles? I think in order to allow annotations in units we would need to remove the fixedPattern rules and add bindings to specific ValueSets. These ValueSets would then include one or multiple entries from the http://unitsofmeasure.org CodeSystem.  
Implementing a parser based _code in ValueSet check_ should be possible, since the HAPI FHIR Validator we are using as part of the process validation step, already supports this against the full http://hl7.org/fhir/ValueSet/ucum-units ValueSet.

**Comment by taneroksuz** [comment]
- Most of the validation errors are fixed. There is only one validation error left. However this error is not related to client 
 side but server side:
- The validation output is given as follows:  
  ```console
  bpe-app-1  | ERROR Grizzly(2) - LogValidationError.logValidationDetails(120) | CRR validation error for https://fhir-store-test.uk-augsburg.science/fhir/Observation/9b22a43accacc42f46c8c69bfba896a547fa7c58f28336e98c97a1f3094af59b/_history/1: StructureDefinition https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/QuelleKlinischesBezugsdatum has no snapshot, and no snapshot generator is configured
  ```
- This error refers to following lines in fhir resources:  
  ```xml
  <effectiveDateTime>
    <extension url="http://hl7.org/fhir/StructureDefinition/data-absent-reason">
      <valueCode value="unknown"/>
    </extension>
  </effectiveDateTime>
  ```
- This error can be fixed as wir replace the **extension** with following line:  
  ```json
  "effectiveDateTime": "1972-01-01T01:00:00+01:00"
  ```
[fhir-bundle.txt](https://github.com/num-codex/codex-processes-ap1/files/9297955/fhir-bundle.txt)

**Comment by franzplri** [comment]
We had an error when validating Blood-Gas-Panel ressources through the DSF. The error always looked like this:

```
app_1 | Validation error for Observation: Profile https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/blood-gas-panel, Element 'Observation.identifier': minimum required = 1, but only found 0

app_1 | Validation error for Observation: Profile https://www.netzwerk-universitaetsmedizin.de/fhir/StructureDefinition/blood-gas-panel, Element 'Observation.identifier[analyseBefundCode]': minimum required = 1, but only found 0
```

Solution:
DSF still had an old version of the blood-gas-panel structure definition stored as a snapshot. 

1. Exit BPE
2. Delete file: /opt/bpe/cache/StructureDefinition/https_www.netzwerk-universitaetsmedizin.de_fhir_StructureDefinition_blood-gas-panel_1.0.5.json.gz
4. Start BPE

The structure definition is reloaded and everything works correctly now.

**Comment by julsas** [comment]
> * Most of the validation errors are fixed. There is only one validation error left. However this error is not related to client
>       side but server side:
> 
>     * The validation output is given as follows:
>       ```
>       bpe-app-1  | ERROR Grizzly(2) - LogValidationError.logValidationDetails(120) | CRR validation error for https://fhir-store-test.uk-augsburg.science/fhir/Observation/9b22a43accacc42f46c8c69bfba896a547fa7c58f28336e98c97a1f3094af59b/_history/1: StructureDefinition https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/QuelleKlinischesBezugsdatum has no snapshot, and no snapshot generator is configured
>       ```
> 
>     * This error refers to following lines in fhir resources:
>       ```
>       <effectiveDateTime>
>         <extension url="http://hl7.org/fhir/StructureDefinition/data-absent-reason">
>           <valueCode value="unknown"/>
>         </extension>
>       </effectiveDateTime>
>       ```
> 
>     * This error can be fixed as wir replace the **extension** with following line:
>       ```json
>       "effectiveDateTime": "1972-01-01T01:00:00+01:00"
>       ```
> 
> 
> [fhir-bundle.txt](https://github.com/num-codex/codex-processes-ap1/files/9297955/fhir-bundle.txt)

This is still an issue? Sounds related to the snapshot generator problem. Snapshot for this extension can be obtained from here: https://simplifier.net/packages/de.medizininformatikinitiative.kerndatensatz.laborbefund/1.0.6/files/388075

@hhund to fix this, couldn't the framework install the StructureDefs with pre-generated snapshots instead of using HAPI's snapshot generator?

**Comment by hhund** [comment]
The false positive validation error about the `QuelleKlinischesBezugsdatum` extensions is/was generated by the [FHIR Bridge](https://github.com/ehrbase/fhir-bridge) component of the NUM-CODEX central research repository during insert of FHIR resources using the extension.

As of today (2022-08-31 17:30) both production and the pre-prod (test) deployments have been fixed via a special release of the [FHIR Bridge](https://github.com/ehrbase/fhir-bridge). The issue is otherwise being tracked at ehrbase/fhir-bridge#581
