### ISSUE TITLE
Only one active instance of trigger process

### ISSUE THREAD

**Issue by wetret** [num-codex/codex-processes-ap1#90]
When starting a new instance of the `trigger` process, check whether an instance is already running and terminate it if necessary. Only one instance of the process should be active at a time.

The MII KDS Report Process, which already implements this feature: 

https://github.com/medizininformatik-initiative/mii-dsf-processes/blob/472addbb053e84285be7a4f5ebd0ecdb3ae717e6/mii-dsf-process-kds-report/src/main/java/de/medizininformatik_initiative/process/kds/report/service/StartTimer.java#L76-L93

**Comment by hhund** [comment]
Bad PR, released via [v0.7.0](https://github.com/num-codex/codex-processes-ap1/releases/tag/v0.7.0)
